/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_vellolayout_free(a: number): void;
export function __wbg_get_vellolayout_n_paths(a: number): number;
export function __wbg_set_vellolayout_n_paths(a: number, b: number): void;
export function __wbg_get_vellolayout_n_clips(a: number): number;
export function __wbg_set_vellolayout_n_clips(a: number, b: number): void;
export function __wbg_get_vellolayout_bin_data_start(a: number): number;
export function __wbg_set_vellolayout_bin_data_start(a: number, b: number): void;
export function __wbg_get_vellolayout_path_tag_base(a: number): number;
export function __wbg_set_vellolayout_path_tag_base(a: number, b: number): void;
export function __wbg_get_vellolayout_path_data_base(a: number): number;
export function __wbg_set_vellolayout_path_data_base(a: number, b: number): void;
export function __wbg_get_vellolayout_draw_tag_base(a: number): number;
export function __wbg_set_vellolayout_draw_tag_base(a: number, b: number): void;
export function __wbg_get_vellolayout_draw_data_base(a: number): number;
export function __wbg_set_vellolayout_draw_data_base(a: number, b: number): void;
export function __wbg_get_vellolayout_transform_base(a: number): number;
export function __wbg_set_vellolayout_transform_base(a: number, b: number): void;
export function __wbg_get_vellolayout_linewidth_base(a: number): number;
export function __wbg_set_vellolayout_linewidth_base(a: number, b: number): void;
export function __wbg_velloconfiguniform_free(a: number): void;
export function __wbg_get_velloconfiguniform_base_color(a: number): number;
export function __wbg_set_velloconfiguniform_base_color(a: number, b: number): void;
export function __wbg_get_velloconfiguniform_layout(a: number): number;
export function __wbg_set_velloconfiguniform_layout(a: number, b: number): void;
export function __wbg_get_velloconfiguniform_binning_size(a: number): number;
export function __wbg_set_velloconfiguniform_binning_size(a: number, b: number): void;
export function __wbg_get_velloconfiguniform_tiles_size(a: number): number;
export function __wbg_set_velloconfiguniform_tiles_size(a: number, b: number): void;
export function __wbg_get_velloconfiguniform_segments_size(a: number): number;
export function __wbg_set_velloconfiguniform_segments_size(a: number, b: number): void;
export function __wbg_get_velloconfiguniform_ptcl_size(a: number): number;
export function __wbg_set_velloconfiguniform_ptcl_size(a: number, b: number): void;
export function __wbg_velloworkgroupsize_free(a: number): void;
export function __wbg_velloworkgroupcounts_free(a: number): void;
export function __wbg_get_velloworkgroupcounts_use_large_path_scan(a: number): number;
export function __wbg_set_velloworkgroupcounts_use_large_path_scan(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_path_reduce(a: number): number;
export function __wbg_set_velloworkgroupcounts_path_reduce(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_path_reduce2(a: number): number;
export function __wbg_set_velloworkgroupcounts_path_reduce2(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_path_scan1(a: number): number;
export function __wbg_set_velloworkgroupcounts_path_scan1(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_path_scan(a: number): number;
export function __wbg_set_velloworkgroupcounts_path_scan(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_bbox_clear(a: number): number;
export function __wbg_set_velloworkgroupcounts_bbox_clear(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_path_seg(a: number): number;
export function __wbg_set_velloworkgroupcounts_path_seg(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_draw_reduce(a: number): number;
export function __wbg_set_velloworkgroupcounts_draw_reduce(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_draw_leaf(a: number): number;
export function __wbg_set_velloworkgroupcounts_draw_leaf(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_clip_reduce(a: number): number;
export function __wbg_set_velloworkgroupcounts_clip_reduce(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_clip_leaf(a: number): number;
export function __wbg_set_velloworkgroupcounts_clip_leaf(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_binning(a: number): number;
export function __wbg_set_velloworkgroupcounts_binning(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_tile_alloc(a: number): number;
export function __wbg_set_velloworkgroupcounts_tile_alloc(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_path_coarse(a: number): number;
export function __wbg_set_velloworkgroupcounts_path_coarse(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_backdrop(a: number): number;
export function __wbg_set_velloworkgroupcounts_backdrop(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_coarse(a: number): number;
export function __wbg_set_velloworkgroupcounts_coarse(a: number, b: number): void;
export function __wbg_get_velloworkgroupcounts_fine(a: number): number;
export function __wbg_set_velloworkgroupcounts_fine(a: number, b: number): void;
export function __wbg_vellobuffersize_free(a: number): void;
export function __wbg_get_vellobuffersize_size_in_bytes(a: number): number;
export function __wbg_set_vellobuffersize_size_in_bytes(a: number, b: number): void;
export function __wbg_vellobuffersizes_free(a: number): void;
export function __wbg_get_vellobuffersizes_path_reduced(a: number): number;
export function __wbg_set_vellobuffersizes_path_reduced(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_path_reduced2(a: number): number;
export function __wbg_set_vellobuffersizes_path_reduced2(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_path_reduced_scan(a: number): number;
export function __wbg_set_vellobuffersizes_path_reduced_scan(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_path_monoids(a: number): number;
export function __wbg_set_vellobuffersizes_path_monoids(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_path_bboxes(a: number): number;
export function __wbg_set_vellobuffersizes_path_bboxes(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_cubics(a: number): number;
export function __wbg_set_vellobuffersizes_cubics(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_draw_reduced(a: number): number;
export function __wbg_set_vellobuffersizes_draw_reduced(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_draw_monoids(a: number): number;
export function __wbg_set_vellobuffersizes_draw_monoids(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_info(a: number): number;
export function __wbg_set_vellobuffersizes_info(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_clip_inps(a: number): number;
export function __wbg_set_vellobuffersizes_clip_inps(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_clip_els(a: number): number;
export function __wbg_set_vellobuffersizes_clip_els(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_clip_bics(a: number): number;
export function __wbg_set_vellobuffersizes_clip_bics(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_clip_bboxes(a: number): number;
export function __wbg_set_vellobuffersizes_clip_bboxes(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_draw_bboxes(a: number): number;
export function __wbg_set_vellobuffersizes_draw_bboxes(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_bump_alloc(a: number): number;
export function __wbg_set_vellobuffersizes_bump_alloc(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_bin_headers(a: number): number;
export function __wbg_set_vellobuffersizes_bin_headers(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_paths(a: number): number;
export function __wbg_set_vellobuffersizes_paths(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_bin_data(a: number): number;
export function __wbg_set_vellobuffersizes_bin_data(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_tiles(a: number): number;
export function __wbg_set_vellobuffersizes_tiles(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_segments(a: number): number;
export function __wbg_set_vellobuffersizes_segments(a: number, b: number): void;
export function __wbg_get_vellobuffersizes_ptcl(a: number): number;
export function __wbg_set_vellobuffersizes_ptcl(a: number, b: number): void;
export function __wbg_renderinfo_free(a: number): void;
export function __wbg_get_renderinfo_ramps_width(a: number): number;
export function __wbg_set_renderinfo_ramps_width(a: number, b: number): void;
export function __wbg_get_renderinfo_ramps_height(a: number): number;
export function __wbg_set_renderinfo_ramps_height(a: number, b: number): void;
export function __wbg_get_renderinfo_images_width(a: number): number;
export function __wbg_set_renderinfo_images_width(a: number, b: number): void;
export function __wbg_get_renderinfo_images_height(a: number): number;
export function __wbg_set_renderinfo_images_height(a: number, b: number): void;
export function renderinfo_scene(a: number): number;
export function renderinfo_ramps(a: number): number;
export function renderinfo_images(a: number): number;
export function renderinfo_layout(a: number): number;
export function renderinfo_config_uniform(a: number): number;
export function renderinfo_workgroup_counts(a: number): number;
export function renderinfo_buffer_sizes(a: number): number;
export function renderinfo_config_bytes(a: number): number;
export function __wbg_velloimage_free(a: number): void;
export function velloimage_id(a: number): number;
export function __wbg_velloencoding_free(a: number): void;
export function velloencoding_new(): number;
export function velloencoding_new_scene(): number;
export function velloencoding_new_image(a: number, b: number): number;
export function velloencoding_append(a: number, b: number): void;
export function velloencoding_append_with_transform(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function velloencoding_reset(a: number, b: number): void;
export function velloencoding_is_empty(a: number): number;
export function velloencoding_linewidth(a: number, b: number): void;
export function velloencoding_matrix(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function velloencoding_svg_path(a: number, b: number, c: number, d: number, e: number): number;
export function velloencoding_insert_path_marker(a: number): void;
export function velloencoding_json_path(a: number, b: number, c: number, d: number, e: number): number;
export function velloencoding_color(a: number, b: number): void;
export function velloencoding_linear_gradient(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function velloencoding_radial_gradient(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number): void;
export function velloencoding_begin_clip(a: number, b: number, c: number, d: number): void;
export function velloencoding_end_clip(a: number): void;
export function velloencoding_image(a: number, b: number, c: number): void;
export function velloencoding_finalize_scene(a: number): void;
export function velloencoding_render(a: number, b: number, c: number, d: number): number;
export function velloencoding_print_debug(a: number): void;
export function run(): void;
export function __wbg_set_velloworkgroupsize_x(a: number, b: number): void;
export function __wbg_set_velloworkgroupsize_y(a: number, b: number): void;
export function __wbg_set_velloworkgroupsize_z(a: number, b: number): void;
export function __wbg_set_vellolayout_n_draw_objects(a: number, b: number): void;
export function __wbg_set_velloconfiguniform_width_in_tiles(a: number, b: number): void;
export function __wbg_set_velloconfiguniform_height_in_tiles(a: number, b: number): void;
export function __wbg_set_velloconfiguniform_target_width(a: number, b: number): void;
export function __wbg_set_velloconfiguniform_target_height(a: number, b: number): void;
export function __wbg_get_velloworkgroupsize_x(a: number): number;
export function __wbg_get_velloworkgroupsize_y(a: number): number;
export function __wbg_get_velloworkgroupsize_z(a: number): number;
export function __wbg_get_vellolayout_n_draw_objects(a: number): number;
export function __wbg_get_velloconfiguniform_width_in_tiles(a: number): number;
export function __wbg_get_velloconfiguniform_height_in_tiles(a: number): number;
export function __wbg_get_velloconfiguniform_target_width(a: number): number;
export function __wbg_get_velloconfiguniform_target_height(a: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_start(): void;
